version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: squizl
      MARIADB_DATABASE: squizl
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]

  squizl-server:
    build: .
    restart: always
    ports: 
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://root:squizl@db:3306/squizl

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - "db"